### ISSUE TITLE
Option `streamcache_adjust_factor` has no effect

### ISSUE THREAD

**Issue by aeph6Ee0** [lvml/mpv-plugin-streamcache#2]
At the beginning of the file, you can set the `streamcache_adjust_factor`:
https://github.com/lvml/mpv-plugin-streamcache/blob/b320dc45bd95dd8ea6af86e00215d7933d440d3e/streamcache.lua#L21
This value is never referenced in the code.
I assume that it should be used when setting the periodic timer.

**Comment by lvml** [comment]
Your observation is correct - but that was the smallest of the existing problems: Actually, I had to heavily modify streamcache.lua to be compatible again with a much-changed caching logic in mpv itself.

Now, the streamcache_adjust_factor is used, amongst all the other changes.

**Comment by aeph6Ee0** [comment]
Thanks a lot. I appreciate your effort.
